Repository Parasuraman-Annadurai/Palli-Application, pull requests merged in 2024-02, with the labels that each got.

#83 Validation
  src/components/AddBatchModule/AddBatch.jsx
  src/components/AssessmentList.jsx
  src/components/AssessmentView.jsx
  src/components/WeightageList.jsx
  src/layouts/Sidebar.jsx
  src/pages/applications/Applications.jsx
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/studentLogin/StudentLogin.jsx
  src/scss/css/style.css
  src/scss/css/style.css.map
  src/scss/style.scss
  src/utils/validate.js
Labels: PR ready for review

#86 Feature/validation
  src/components/AssessmentList.jsx
  src/components/AssessmentView.jsx
  src/components/WeightageList.jsx
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/studentLogin/StudentLogin.jsx
  src/scss/css/style.css
  src/scss/css/style.css.map
  src/scss/style.scss
  src/utils/validate.js
Labels: PR ready for review

#85 Comments
  index.html
  public/icons/Palli Fav icon.svg
  public/icons/Send.svg
  public/icons/comment-border.svg
  public/icons/comment-fill.svg
  src/components/AssessmentView.jsx
  src/components/CommentsModule/Comments.jsx
  src/components/CommentsModule/scss/Comments.css
  src/components/CommentsModule/scss/Comments.css.map
  src/components/CommentsModule/scss/Comments.scss
  src/components/WeightageList.jsx
  src/layouts/Sidebar.jsx
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/studentLogin/StudentLogin.jsx
  src/pages/studentLogin/scss/StudentLogin.css
  src/pages/studentLogin/scss/StudentLogin.css.map
  src/pages/studentLogin/scss/StudentLogin.scss
  src/scss/css/style.css
  src/scss/css/style.css.map
  src/scss/style.scss
Labels: Request Changes

#88 Feature/permissions
  src/components/AddBatchModule/AddBatch.jsx
  src/components/AssessmentList.jsx
  src/components/AssessmentView.jsx
  src/components/WeightageList.jsx
  src/layouts/Sidebar.jsx
  src/pages/applications/Applications.jsx
  src/pages/login/Login.jsx
  src/utils/validate.js
Labels: PR ready for review

#89 API permission added
  src/components/AddBatchModule/AddBatch.jsx
  src/components/AssessmentView.jsx
  src/components/CommentsModule/Comments.jsx
  src/layouts/Sidebar.jsx
  src/pages/applications/Applications.jsx
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/login/Login.jsx
  src/pages/studentLogin/StudentLogin.jsx
Labels: PR ready for review

#91 comments section changes as per design
  src/components/AssessmentView.jsx
  src/components/CommentsModule/Comments.jsx
  src/layouts/Sidebar.jsx
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/studentLogin/StudentLogin.jsx
  src/utils/validate.js
Labels: PR ready for review

#94 major bug fixed
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/login/Login.jsx
Labels: PR ready for review

#95 Feature/UI design changes
  public/icons/comment-fill-hover.svg
  public/icons/delete-icon-hover.svg
  public/icons/edit-icon-hover.svg
  public/icons/edit-pencil-icon.svg
  public/icons/logout-hover.svg
  public/icons/logout.svg
  public/icons/task Active.svg
  public/icons/task default.svg
  src/components/AddBatchModule/AddBatch.jsx
  src/components/AddBatchModule/scss/AddBatch.css
  src/components/AddBatchModule/scss/AddBatch.css.map
  src/components/AddBatchModule/scss/AddBatch.scss
  src/components/AssessmentList.jsx
  src/components/AssessmentView.jsx
  src/components/CommentsModule/Comments.jsx
  src/components/CommentsModule/scss/Comments.css
  src/components/CommentsModule/scss/Comments.css.map
  src/components/CommentsModule/scss/Comments.scss
  src/layouts/Sidebar.jsx
  src/pages/applications/Applications.jsx
  src/pages/applications/scss/Applications.scss
  src/pages/applications/scss/css/Applications.css
  src/pages/applications/scss/css/Applications.css.map
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/studentLogin/scss/StudentLogin.css
  src/pages/studentLogin/scss/StudentLogin.css.map
  src/pages/studentLogin/scss/StudentLogin.scss
  src/scss/css/style.css
  src/scss/css/style.css.map
  src/scss/style.css
  src/scss/style.css.map
  src/scss/style.scss
Labels: PR ready for review

#97 Feature/bug fixing
  package-lock.json
  package.json
  public/icons/application.svg
  public/icons/application_active.svg
  public/icons/application_icon.svg
  public/icons/task_active.svg
  public/icons/task_icon.svg
  src/components/AddBatchModule/AddBatch.jsx
  src/components/AssessmentList.jsx
  src/components/AssessmentView.jsx
  src/components/CommentsModule/Comments.jsx
  src/components/PasswordRequirement/PasswordRequirement.jsx
  src/components/WeightageList/WeightageList.jsx
  src/components/WeightageList/scss/WeightageList.css
  src/components/WeightageList/scss/WeightageList.css.map
  src/components/WeightageList/scss/WeightageList.scss
  src/layouts/Navbar.jsx
  src/layouts/Sidebar.jsx
  src/pages/applications/Applications.jsx
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/dashBoard/DashBoard.jsx
  src/pages/login/Login.jsx
  src/pages/studentLogin/StudentLogin.jsx
  src/routes/PrivateRoute.jsx
  src/scss/css/style.css
  src/scss/css/style.css.map
  src/scss/style.scss
  src/utils/validate.js
Labels: PR ready for review

#115 application menu permission fixed
  src/layouts/Sidebar.jsx
Labels: PR ready for merge

#116 comments empty issue fixed
  src/components/AssessmentView.jsx
Labels: PR ready for merge

#117 student work view ui issue fixed
  src/components/AssessmentView.jsx
  src/components/CommentsModule/Comments.jsx
  src/pages/assessmentModule/AssessmentModule.jsx
  src/pages/login/Login.jsx
  src/scss/css/style.css
  src/scss/css/style.css.map
  src/scss/style.scss
Labels: PR ready for merge
